# Generated by Django 4.1 on 2024-11-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=200)),
                ("checked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
