# Generated by Django 4.1 on 2024-11-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="todo_id",
            field=models.CharField(default="", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
