# Generated by Django 4.1 on 2024-11-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_todo_todo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="position",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
