# Generated by Django 4.1 on 2024-11-15 13:16

from django.db import migrations, models
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_todo_position"),
    ]

    operations = [
        migrations.RemoveField(model_name="todo", name="id",),
        migrations.AlterField(
            model_name="todo",
            name="position",
            field=models.FloatField(default=todos.models.set_position),
        ),
        migrations.AlterField(
            model_name="todo",
            name="todo_id",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
